### ISSUE TITLE
很好的学习素材，不过不会担心block引起的循环引用吗？

### ISSUE THREAD

**Issue by zenghaojim33** [guojiubo/PlainReader#1]
我看大部分的block嵌套都没有用到weakself strongself

**Comment by guojiubo** [comment]
不知道你指的具体是哪里？哪个文件，哪行代码？

**Comment by zenghaojim33** [comment]
比如说PRHTTPFetcher下的
- (void)fetchHomePage:(CWHTTPFetcherBlock)block
  {
  AFHTTPRequestOperationManager *m = [self HTTPRequestOperationManager];
  self.requestOperation = [m GET:@"http://www.cnbeta.com" parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
      dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
          TFHpple *hpple = [[TFHpple alloc] initWithHTMLData:operation.responseData];
          NSArray *items = [hpple searchWithXPathQuery:@"//div[@class=\"all_news_wildlist\"]//div[@class=\"item\"]"];
          if ([items count] == 0) {
              self.error = [self serverError];
              [self safelyCallback:block];
              return;
          }
  
  ```
      // TOKEN
      NSString *wholeHTML = [[NSString alloc] initWithData:hpple.data encoding:NSUTF8StringEncoding];
      if (wholeHTML) {
          NSRegularExpression *reg = [NSRegularExpression regularExpressionWithPattern:@"TOKEN:\"([^\"]*)\"" options:NSRegularExpressionCaseInsensitive error:nil];
          NSTextCheckingResult *match = [reg firstMatchInString:wholeHTML options:0  range:NSMakeRange(0, wholeHTML.length)];
          if (match.numberOfRanges > 0) {
              CBHomePageToken = [wholeHTML substringWithRange:[match rangeAtIndex:1]];
          }
      }
  
      for (TFHppleElement *element in items) {
          PRArticle *article = [[PRArticle alloc] init];
          NSString *divId = [element objectForKey:@"id"];
          NSString *articleIdString = [[divId componentsSeparatedByCharactersInSet:[[NSCharacterSet decimalDigitCharacterSet] invertedSet]] componentsJoinedByString:@""];
          article.articleId = @([articleIdString integerValue]);
          article.title = [[[element findFirstSubnodeWithClassName:@"title"] findFirstSubnodeWithTagName:@"a"] text];
          article.pubTime = [[[element findFirstSubnodeWithClassName:@"tj"] findFirstSubnodeWithTagName:@"em"] text];
          NSString *commentCountString = [[[element findFirstSubnodeWithClassName:@"gray"] findFirstSubnodeWithTagName:@"em"] text];
          article.commentCount = @([commentCountString integerValue]);
          article.thumb = [[[element findFirstSubnodeWithClassName:@"picno"] findFirstSubnodeWithTagName:@"img"] objectForKey:@"src"];
  
          [[PRDatabase sharedDatabase] storeArticle:article];
      }
  
      [self safelyCallback:block];
  });
  ```
  
  } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
      self.error = error;
      [self safelyCallback:block];
  }];
  }
  这种频繁出现self的block不用weakself不会造成引用循环吗？
  我在v2ex的开源客户端看到的都是有使用weakself和strongself的

**Comment by guojiubo** [comment]
OK，这里是不需要担心 retain cycle 的。
原因概括说来就是:
AFHTTPRequestOperationManager 的 success 和 failure block 确实持有了 fetcher 对象没错，但是 fetcher 对象并没有持有这两个 block。
