### ISSUE TITLE
三个错误

### ISSUE THREAD

**Issue by mxm145** [guojiubo/PlainReader#2]
为直接下载你的代码在xcode 6.4下打开运行有三个错误：
haseScriptExecution Check\ Pods\ Manifest.lock /Users/lemon/Library/Developer/Xcode/DerivedData/PlainReader-gwqntizipnhedoecaugljjaaojdl/Build/Intermediates/PlainReader.build/Debug-iphonesimulator/PlainReader.build/Script-C41ADB169ECF4FB0A5D59AC4.sh
    cd /Users/lemon/Desktop/PlainReader
    /bin/sh -c /Users/lemon/Library/Developer/Xcode/DerivedData/PlainReader-gwqntizipnhedoecaugljjaaojdl/Build/Intermediates/PlainReader.build/Debug-iphonesimulator/PlainReader.build/Script-C41ADB169ECF4FB0A5D59AC4.sh

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
![2015-07-07 15 10 47](https://cloud.githubusercontent.com/assets/869702/8540667/6d17d364-24ba-11e5-853c-f54a07be5b8c.png)
我是新手，能帮我解决一下吗？

**Comment by guojiubo** [comment]
试试下面的解决方案吧：

```
http://stackoverflow.com/questions/17072396/cocoapods-errors-on-project-build
```
