### ISSUE TITLE
Missing Submodule pop.pop

### ISSUE THREAD

**Issue by shiltian** [guojiubo/PlainReader#3]
在 PlainReader-Bridging-Header.h 里面有一句 #'import <pop.h，这一句是 Warning，然后下面错误就有 Use of undeclared type 'CWStackController' 和 Use of unsolved identifier 'CW_HEXColor'.
不知道是不是由于那个 warning 引起的？

**Comment by guojiubo** [comment]
@tianshilei1992 我这并没有发现你所说的问题，请问你安装 CocoaPods 依赖库了吗？

**Comment by shiltian** [comment]
感谢回复。

我已经运行了 pods install 了，所有的依赖库应该都安装了。

哦对了，我用的是 Xcode 7.1 Beta。

2015-09-17 21:08 GMT+08:00 guojiubo notifications@github.com:

> 我这并没有发现你所说的问题，请问你安装 CocoaPods 依赖库了吗？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guojiubo/PlainReader/issues/3#issuecomment-141077549.

## 

---

Sincerely yours,

Shilei Tian（田世磊）
Postgraduate Student
Department of Computer Science and Engineering
Shanghai Jiao Tong University

**Comment by guojiubo** [comment]
@tianshilei1992 Xcode 7 暂时没有测试过，我的环境目前是 Xcode 6.4，如果你还保留有 Xcode 6 的话可以切换过去试试，应该是没有问题的。

**Comment by shiltian** [comment]
好的，知道了，谢谢！

在 2015年9月17日 下午9:15，guojiubo notifications@github.com写道：

> @tianshilei1992 https://github.com/tianshilei1992 Xcode 7
> 暂时没有测试过，我的环境目前是 Xcode 6.4，如果你还保留有 Xcode 6 的话可以切换过去试试，应该是没有问题的。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guojiubo/PlainReader/issues/3#issuecomment-141079888.

## 

---

Sincerely yours,

Shilei Tian（田世磊）
Postgraduate Student
Department of Computer Science and Engineering
Shanghai Jiao Tong University

**Comment by guojiubo** [comment]
Xcode 7.1.1 正式版测试未发现问题。
