### ISSUE TITLE
Canot fetch news

### ISSUE THREAD

**Issue by mailbyms** [guojiubo/PlainReader#4]
Since last month? CNBETA might change API. Please have a look at it, thanks.

**Comment by shiltian** [comment]
是的，确实是换了 API，比如文章的链接，Load More 的链接都换了。因为最近我在考虑模仿你的那个写一个，所以也在研究。


----------

Sincerely yours,

Shilei Tian

**Comment by guojiubo** [comment]
官方改版，接口失效了，我暂时没有精力继续维护，但是依然接受PR
